import Document, { Html, Head, Main, NextScript } from 'next/document';

export default class MyDocument extends Document {
    render() {
        return (
            <Html>
                <Head>
                    <meta name='description' content='Generated by create next app' />
                    <meta name='keywords' content='beer,food,search,alcohol' />
                    <link rel='icon' href='/favicon.ico' />
                    <title>Reddit</title>
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </Html>
        );
    }
}
